### PR TITLE
Add automatic configuration and build scripts using GNU autotools.

### PR DESCRIPTION
**Pull request by maaku**
The following should work to build and install libsha2 on most platforms:
    ./autogen.sh  # Recreate ./configure using GNU autotools
    ./configure
    make check
    make install

### CODE REVIEW

**Comment by maandree** [comment]
I appreciate the effort, but I don't want to use the GNU autotools. I will be using another system later on.

**Comment by maaku** [comment]
That's disappointing :(

I'm doing due diligence evaluating libsha2 for use in a project at work, for which autotools integration is a necessity. It will be somewhat annoying to maintain a separate branch.

**Comment by maandree** [comment]
Why is it necessary for libsha2 to use GNU autotools for your project to use it?

**Comment by maaku** [comment]
We support various obscure embedded devices that don't always have
"typical" compiler features. Programs which rely on standard autotools
configuration results compile and behave as expected. Nontraditional build
tools aren't so easy to maintain.

We also do cross compilation as part of our integration testing and
deployment process. Autotools makes this easy and uniform across all
packages.

As an example of how autotools helps, without getting into obscure
platforms, the 'restrict' keyword is now supported by GCC with standard
build options on Ubuntu 15.10's toolchain. There is a '__restrict' keyword
though, and this PR will autodetect and add a define to the
libsha2-config.h file. (This was needed for me to compile he library on my
laptop.)

**Pull request closed without merging**
